sync:
  image: n3llyb0y/wait
  links:
    - ari
  environment:
    PORTS: "5039"
    TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

ari:
  image: wazopbx/asterisk
  ports:
    - "5039"
  volumes:
    - "./etc/asterisk:/etc/asterisk"
  command: "asterisk -fTvvv"
