version: "3"
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  ari:
    image: wazopbx/asterisk
    ports:
      - "5039"
    volumes:
      - "./etc/asterisk:/etc/asterisk"
    command: "asterisk -fTvvv"
